### ISSUE TITLE
ユーザーは他のユーザーをブロック出来る

### ISSUE THREAD

**Issue by Karibash** [looks-to-me/looks-to-me#11]
# Goal

- ユーザーは他のユーザーをブロック出来る
- ブロックしたユーザーの投稿は表示されなくなる

**Comment by penpendayo** [comment]
## 前提
やりたいことはブロックではなくて、ミュートだと思ったので全部ミュートに置き換えています。

現状だと「この人の投稿うざいな」とは思っても「この人に投稿を見られたくないな」とは思わない気がするからです。

「この人に投稿を見られたくないな」という機能がほしい場合は、それはブロック機能として別に実装した方がいい気がします。

## 機能要件

1. ログインユーザーは、他のユーザーをミュートできる
    1. ミュートする前に「本当にいいの？」なモーダルが表示される
    2. ミュート後、「ミュートしました」的なトーストが表示される
2. ログインユーザーは、他のユーザーをミュート解除できる
    1. ミュート解除する前に「本当にいいの？」なモーダルが表示される
    2. ミュート解除後、「ミュート解除しました」的なトーストが表示される
3. ログインユーザーが、「ミュートしているユーザー」のユーザーページに行くと「このユーザーはミュート済みです」と表示される
   1. ミュート済みの場合、投稿も見れない
4. ログインユーザーは、ミュートしているユーザーの一覧を確認できる
5. ~~ログインユーザーは、自分をミュートしているユーザーの数を確認できる~~

**Comment by penpendayo** [comment]
残りタスク

- [ ] ユーザーページでMute・Unmuteができる
- [ ]  「ミュートしているユーザー」のユーザーページに行くと「このユーザーはミュート済みです」的な表示される
