### ISSUE TITLE
ユーザーは投稿を追加出来る

### ISSUE THREAD

**Issue by Karibash** [looks-to-me/looks-to-me#7]
# Goal

- アカウント登録したユーザーは投稿を追加出来る
- 投稿時には画像、重ねる文字列(英数字のみ/最大10文字)、タグ(最大5件)を指定出来る
  - Goodを指定時はLooksGoodToMeを画像の上に重ねる
  - タグは投稿検索時に用いられる
  - 文字色は白/黒を画像の相対輝度を元に自動で切り替えるようにしたい (可能であれば
  - 画像の拡張子は jpeg/png/gif には最低限対応する

# dev tasks

- [x] #58
- [x] #57
- [x] #59
- [x] #60
- [x] #61
- [x] #62
- [x] #63

**Comment by wooootack** [comment]
### 想定している処理の流れ

- ユーザーがアップロードした画像は[R2](https://www.cloudflare.com/ja-jp/products/r2/)に保存する予定
- 画像投稿のフローは↓みたいな感じで考えています。
  - ユーザーが画像を投稿する
    - ファイルサイズ制限掛けておく
  - 画像を保存する
    - 画像IDを発行する
    - 無加工の画像をR2に保存する
  - 投稿を保存する
    - 投稿IDを発行する
    - 画像に重ねる文字列と画像IDをDBへ保存する
  - Rustで作った画像加工Workerを[ServiceBindings](https://developers.cloudflare.com/workers/platform/bindings/about-service-bindings/)で呼び出す
    - 投稿ID、画像のURL、画像に重ねる文字列をinputにする
    - 画像を加工し、投稿IDを使用してCloudflareImagesへ[アップロード](https://developers.cloudflare.com/images/cloudflare-images/upload-images/custom-id/)する

**Comment by wooootack** [comment]
現状の投稿追加まわりのフロー

![Image](https://github.com/looks-to-me/looks-to-me/assets/40280508/c6fc98bc-cbda-4905-9e20-68dc77cfffe9)
